# Numpy

In [1]:
import numpy as np

In [220]:
a=np.array([1,2,3],dtype="int64");
print(a)

[1 2 3]


In [221]:
b=np.array([[1,2,3],[4,5,9]])
print(b)

[[1 2 3]
 [4 5 9]]


In [222]:
b.ndim

2

In [223]:
b.shape

(2, 3)

In [224]:
a.shape

(3,)

In [225]:
a.dtype

dtype('int64')

In [226]:
a.nbytes

24

In [227]:
a.itemsize

8

In [2]:
alpha=np.array([[1,2,3,4,5],[7,8,9,10,11]])



In [3]:
alpha.shape

(2, 5)

In [4]:
print(alpha)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


In [8]:
print(alpha[:,0])

[1 7]


In [11]:
alpha[:,0:-2:2]

array([[1, 3],
       [7, 9]])

In [233]:
print(alpha)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


In [234]:
alpha[:,2]=5
print(alpha)

[[ 1  2  5  4  5]
 [ 7  8  5 10 11]]


In [12]:
beta=np.array([ [[1,2,3],[4,5,6],[7,8,9]] , [[10,11,12],[13,14,15],[16,17,18]] ]);

In [13]:
beta.shape

(2, 3, 3)

In [237]:
print(beta)
print("\n-------\n")
print(beta[0][:][0])
print("\n-------\n")
print(beta[0,:,1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]

-------

[1 2 3]

-------

[2 5 8]


In [238]:
beta[:,1,:]

array([[ 4,  5,  6],
       [13, 14, 15]])

In [239]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [240]:
np.ones((3,2,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [241]:
np.full_like(alpha,4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [242]:
np.random.rand(2,2,3)

array([[[0.28929528, 0.6253326 , 0.86170185],
        [0.85992374, 0.15764228, 0.73546912]],

       [[0.28164017, 0.85973141, 0.57080759],
        [0.07768634, 0.81500853, 0.00444461]]])

In [243]:
np.random.random_sample(beta.shape)

array([[[7.60547800e-01, 4.26016323e-01, 6.68900799e-01],
        [9.52182947e-04, 9.99376101e-01, 4.46715075e-01],
        [7.22304317e-01, 3.72003241e-01, 6.20087008e-01]],

       [[9.91029556e-01, 2.22793492e-01, 6.21784687e-01],
        [4.48146785e-01, 5.60877725e-01, 2.99844806e-01],
        [9.54565288e-01, 3.39838101e-01, 6.99745479e-01]]])

In [244]:
test=np.random.randint(10,size=(3,3,3),dtype="int32")
print(test)
test.nbytes

[[[2 2 5]
  [4 2 2]
  [8 7 0]]

 [[4 6 3]
  [0 9 9]
  [0 2 4]]

 [[7 3 7]
  [0 4 8]
  [5 9 7]]]


108

In [245]:
5*np.identity(3)

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [246]:
x = np.array([[1,2],[3,4]])
print(beta)
np.repeat(beta, 2, axis=2)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


array([[[ 1,  1,  2,  2,  3,  3],
        [ 4,  4,  5,  5,  6,  6],
        [ 7,  7,  8,  8,  9,  9]],

       [[10, 10, 11, 11, 12, 12],
        [13, 13, 14, 14, 15, 15],
        [16, 16, 17, 17, 18, 18]]])

In [247]:
np.full_like(beta,4)

array([[[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]]])

In [248]:
np.random.random_sample(beta.shape)

array([[[0.49434186, 0.15024322, 0.99860229],
        [0.45488188, 0.0360906 , 0.45616352],
        [0.09728151, 0.5343966 , 0.40894303]],

       [[0.73668962, 0.36923187, 0.01701183],
        [0.96893574, 0.18720463, 0.60382424],
        [0.97924598, 0.8089138 , 0.6556557 ]]])

In [249]:
np.random.rand(2,3,3)

array([[[0.10970812, 0.1487986 , 0.11923019],
        [0.67146029, 0.36906131, 0.9522744 ],
        [0.46060609, 0.57448966, 0.59210408]],

       [[0.37701205, 0.92003879, 0.65767855],
        [0.37294079, 0.48572942, 0.77822193],
        [0.203558  , 0.61274309, 0.27866773]]])

In [250]:
np.random.randint(6,7,size=beta.shape)

array([[[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]],

       [[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]])

In [251]:
vvi=np.ones((5,5));
xo=np.full((3,3),0);
vvi[1:4][:,1:4]=xo;
vvi[2][2]=9;
print("\n-------------\n")
print(vvi)


-------------

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [252]:
a=np.array([1,2,3],dtype="float");
b=a.copy();
b[0]=99.9;
print(a);

[1. 2. 3.]


In [253]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [254]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
c=np.matmul(a,b);
print(c);
np.linalg.det(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


0.0

In [255]:
filedata=np.genfromtxt("data.txt",delimiter=",",dtype="int32");
filedata[True]

array([[[ 1,  2, -3,  0,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]]], dtype=int32)

In [256]:
a=np.array([1,2,3,4]);
a[[False,True,False,True]]

array([2, 4])

In [257]:
a[[0,2,1,3]]

array([1, 3, 2, 4])

# Pandas

In [258]:
import pandas as pd

In [259]:
dict1={
    "name":["sourjya","basu","rick"],
    "age":[23,18,24],
    "marks":[92,97,88]
};

In [260]:
df=pd.DataFrame(dict1)

In [261]:
df.to_csv("hello.txt");

In [262]:
df.describe()

age      marks
count   3.000000   3.000000
mean   21.666667  92.333333
std     3.214550   4.509250
min    18.000000  88.000000
25%    20.500000  90.000000
50%    23.000000  92.000000
75%    23.500000  94.500000
max    24.000000  97.000000

In [263]:
df.head(1)

name  age  marks
0  sourjya   23     92

In [264]:
train=pd.read_csv("train.csv")

In [265]:
train

name  speed         city
0  sourjya     23     vadodara
1     basu     18        surat
2     rick     24  gandhinagar

In [266]:
train["speed"][0]=50

/tmp/ipykernel_2501/2920635934.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  train["speed"][0]=50
/tmp/ipykernel_2501/2920635934.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the 

In [267]:
train

name  speed         city
0  sourjya     50     vadodara
1     basu     18        surat
2     rick     24  gandhinagar

In [268]:
df.columns[0]

'name'

In [269]:
train.to_csv("train1.csv",index=True);

In [270]:
train.index=["a","b","c"]

In [271]:
train

name  speed         city
a  sourjya     50     vadodara
b     basu     18        surat
c     rick     24  gandhinagar

In [272]:
type(train)

pandas.core.frame.DataFrame

In [273]:
type(pd.Series(np.random.rand(10)))

pandas.core.series.Series

In [274]:
np.arange(334)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [275]:
newdf=pd.DataFrame(np.random.rand(334,5),index=1+np.arange(334))
newdf.head()

0         1         2         3         4
1  0.059310  0.085597  0.526608  0.866975  0.160225
2  0.704846  0.273390  0.757600  0.692157  0.987609
3  0.474677  0.149488  0.578163  0.716557  0.327269
4  0.823744  0.850481  0.884853  0.176255  0.179566
5  0.406723  0.666363  0.247438  0.004502  0.817327

In [276]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [277]:
newdf[0][0] = 124

/tmp/ipykernel_2501/426065390.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0] = 124


In [278]:
newdf.head()

0         1         2         3         4
1  0.059310  0.085597  0.526608  0.866975  0.160225
2  0.704846  0.273390  0.757600  0.692157  0.987609
3  0.474677  0.149488  0.578163  0.716557  0.327269
4  0.823744  0.850481  0.884853  0.176255  0.179566
5  0.406723  0.666363  0.247438  0.004502  0.817327

In [279]:
newdf.to_numpy().dtype

dtype('float64')

In [280]:
newdf

0         1         2         3         4
1    0.059310  0.085597  0.526608  0.866975  0.160225
2    0.704846  0.273390  0.757600  0.692157  0.987609
3    0.474677  0.149488  0.578163  0.716557  0.327269
4    0.823744  0.850481  0.884853  0.176255  0.179566
5    0.406723  0.666363  0.247438  0.004502  0.817327
..        ...       ...       ...       ...       ...
330  0.785849  0.814131  0.041565  0.188848  0.721388
331  0.853107  0.771688  0.250508  0.087661  0.038315
332  0.033780  0.926594  0.211243  0.548711  0.367709
333  0.776703  0.952058  0.848862  0.346143  0.585943
334  0.137914  0.820643  0.403255  0.717812  0.674899

[334 rows x 5 columns]

In [281]:
newdf.T

1         2         3         4         5         6         7    \
0  0.059310  0.704846  0.474677  0.823744  0.406723  0.136744  0.786014   
1  0.085597  0.273390  0.149488  0.850481  0.666363  0.227788  0.775941   
2  0.526608  0.757600  0.578163  0.884853  0.247438  0.579106  0.034835   
3  0.866975  0.692157  0.716557  0.176255  0.004502  0.368356  0.246392   
4  0.160225  0.987609  0.327269  0.179566  0.817327  0.970449  0.640579   

        8         9         10   ...       325       326       327       328  \
0  0.067641  0.951896  0.650471  ...  0.046686  0.048350  0.626856  0.995522   
1  0.914135  0.446905  0.847686  ...  0.788150  0.261703  0.568342  0.639972   
2  0.315368  0.982547  0.409304  ...  0.363153  0.297265  0.525800  0.562109   
3  0.354777  0.584615  0.336283  ...  0.363021  0.950678  0.179127  0.116873   
4  0.732610  0.371758  0.932102  ...  0.554052  0.198390  0.506477  0.655763   

        329       330       331       332       333       334  
0  0.426065  0.785849  0.853107  0.033780  0.776703  0.137914  
1  0.222072  0.814131  0.771688  0.926594  0.952058  0.820643  
2  0.085815  0.041565  0.250508  0.211243  0.848862  0.403255  
3  0.511963  0.188848  0.087661  0.548711  0.346143  0.717812  
4  0.820936  0.721388  0.038315  0.367709  0.585943  0.674899  

[5 rows x 334 columns]

In [282]:
newdf.sort_index(axis=1,ascending=False).sort_index(axis=0,ascending=False)

4         3         2         1         0
334  0.674899  0.717812  0.403255  0.820643  0.137914
333  0.585943  0.346143  0.848862  0.952058  0.776703
332  0.367709  0.548711  0.211243  0.926594  0.033780
331  0.038315  0.087661  0.250508  0.771688  0.853107
330  0.721388  0.188848  0.041565  0.814131  0.785849
..        ...       ...       ...       ...       ...
5    0.817327  0.004502  0.247438  0.666363  0.406723
4    0.179566  0.176255  0.884853  0.850481  0.823744
3    0.327269  0.716557  0.578163  0.149488  0.474677
2    0.987609  0.692157  0.757600  0.273390  0.704846
1    0.160225  0.866975  0.526608  0.085597  0.059310

[334 rows x 5 columns]

In [297]:
 newdf.columns=["A","B","C","D","E"]
# newdf=newdf.drop("F",axis=1)
newdf

A         B         C         D         E
1    0.059310  0.085597  0.526608  0.866975  0.160225
2    0.704846  0.273390  0.757600  0.692157  0.987609
3    0.474677  0.149488  0.578163  0.716557  0.327269
4    0.823744  0.850481  0.884853  0.176255  0.179566
5    0.406723  0.666363  0.247438  0.004502  0.817327
..        ...       ...       ...       ...       ...
330  0.785849  0.814131  0.041565  0.188848  0.721388
331  0.853107  0.771688  0.250508  0.087661  0.038315
332  0.033780  0.926594  0.211243  0.548711  0.367709
333  0.776703  0.952058  0.848862  0.346143  0.585943
334  0.137914  0.820643  0.403255  0.717812  0.674899

[334 rows x 5 columns]

In [298]:
newdf.loc[1,"A"]=654
newdf.head(2)

A         B         C         D         E
1  654.000000  0.085597  0.526608  0.866975  0.160225
2    0.704846  0.273390  0.757600  0.692157  0.987609

In [299]:
newdf

A         B         C         D         E
1    654.000000  0.085597  0.526608  0.866975  0.160225
2      0.704846  0.273390  0.757600  0.692157  0.987609
3      0.474677  0.149488  0.578163  0.716557  0.327269
4      0.823744  0.850481  0.884853  0.176255  0.179566
5      0.406723  0.666363  0.247438  0.004502  0.817327
..          ...       ...       ...       ...       ...
330    0.785849  0.814131  0.041565  0.188848  0.721388
331    0.853107  0.771688  0.250508  0.087661  0.038315
332    0.033780  0.926594  0.211243  0.548711  0.367709
333    0.776703  0.952058  0.848862  0.346143  0.585943
334    0.137914  0.820643  0.403255  0.717812  0.674899

[334 rows x 5 columns]

In [300]:
newdf.loc[[1,2,3]]

A         B         C         D         E
1  654.000000  0.085597  0.526608  0.866975  0.160225
2    0.704846  0.273390  0.757600  0.692157  0.987609
3    0.474677  0.149488  0.578163  0.716557  0.327269

In [304]:
newdf.loc[(newdf['A']<0.3)&(newdf['A']>0.25)]

A         B         C         D         E
35   0.290025  0.639107  0.577230  0.067239  0.691781
72   0.282639  0.328953  0.763093  0.633614  0.221357
151  0.261732  0.536133  0.929875  0.062428  0.703657
212  0.297336  0.785785  0.803155  0.046315  0.274754
266  0.285925  0.238745  0.365367  0.229254  0.194759
286  0.289008  0.231490  0.897841  0.711679  0.331920
290  0.259502  0.051936  0.222065  0.329164  0.967977
300  0.298888  0.046973  0.152937  0.506529  0.843929
314  0.290768  0.743975  0.349041  0.186369  0.991513
317  0.272412  0.282690  0.829738  0.996121  0.239908

In [288]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
A    float64
dtype: object

In [310]:
newdf.iloc[0,4]

0.1602250720128009

In [311]:
newdf

A         B         C         D         E
1    654.000000  0.085597  0.526608  0.866975  0.160225
2      0.704846  0.273390  0.757600  0.692157  0.987609
3      0.474677  0.149488  0.578163  0.716557  0.327269
4      0.823744  0.850481  0.884853  0.176255  0.179566
5      0.406723  0.666363  0.247438  0.004502  0.817327
..          ...       ...       ...       ...       ...
330    0.785849  0.814131  0.041565  0.188848  0.721388
331    0.853107  0.771688  0.250508  0.087661  0.038315
332    0.033780  0.926594  0.211243  0.548711  0.367709
333    0.776703  0.952058  0.848862  0.346143  0.585943
334    0.137914  0.820643  0.403255  0.717812  0.674899

[334 rows x 5 columns]

In [318]:
#newdf.drop([3],inplace=True)
newdf.head(10)

A         B         C         D         E
1   654.000000  0.085597  0.526608  0.866975  0.160225
2     0.704846  0.273390  0.757600  0.692157  0.987609
4     0.823744  0.850481  0.884853  0.176255  0.179566
5     0.406723  0.666363  0.247438  0.004502  0.817327
6     0.136744  0.227788  0.579106  0.368356  0.970449
7     0.786014  0.775941  0.034835  0.246392  0.640579
8     0.067641  0.914135  0.315368  0.354777  0.732610
9     0.951896  0.446905  0.982547  0.584615  0.371758
10    0.650471  0.847686  0.409304  0.336283  0.932102
11    0.331210  0.110739  0.654302  0.737724  0.673374

In [321]:
newdf.reset_index(drop=True,inplace=True)

In [322]:
newdf.head(5)

A         B         C         D         E
0  654.000000  0.085597  0.526608  0.866975  0.160225
1    0.704846  0.273390  0.757600  0.692157  0.987609
2    0.823744  0.850481  0.884853  0.176255  0.179566
3    0.406723  0.666363  0.247438  0.004502  0.817327
4    0.136744  0.227788  0.579106  0.368356  0.970449

In [329]:
newdf.loc[:,['B']]=56
newdf.head(5)

A   B         C         D         E
0  654.000000  56  0.526608  0.866975  0.160225
1    0.704846  56  0.757600  0.692157  0.987609
2    0.823744  56  0.884853  0.176255  0.179566
3    0.406723  56  0.247438  0.004502  0.817327
4    0.136744  56  0.579106  0.368356  0.970449

In [326]:
newdf['B'].isnull()

0      True
1      True
2      True
3      True
4      True
       ... 
328    True
329    True
330    True
331    True
332    True
Name: B, Length: 333, dtype: bool

In [359]:

# newdf.drop((5,"D"),axis=1,inplace=True)
newdf["D"][2]=None
newdf["F"]=None
print(newdf)
newdf.dropna(how="all",axis=1).head()
# newdf.head()

              A   B         C         D         E     F
0    654.000000  56  0.526608  0.866975  0.160225  None
1      0.704846  56  0.757600  0.692157  0.987609  None
2      0.823744  56  0.884853       NaN  0.179566  None
3      0.406723  56  0.247438  0.004502  0.817327  None
4      0.136744  56  0.579106  0.368356  0.970449  None
..          ...  ..       ...       ...       ...   ...
328    0.785849  56  0.041565  0.188848  0.721388  None
329    0.853107  56  0.250508  0.087661  0.038315  None
330    0.033780  56  0.211243  0.548711  0.367709  None
331    0.776703  56  0.848862  0.346143  0.585943  None
332    0.137914  56  0.403255  0.717812  0.674899  None

[333 rows x 6 columns]


/tmp/ipykernel_2501/3319864225.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf["D"][2]=None
/tmp/ipykernel_2501/3319864225.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the ca

A   B         C         D         E
0  654.000000  56  0.526608  0.866975  0.160225
1    0.704846  56  0.757600  0.692157  0.987609
2    0.823744  56  0.884853       NaN  0.179566
3    0.406723  56  0.247438  0.004502  0.817327
4    0.136744  56  0.579106  0.368356  0.970449