In [10]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

data=pd.read_csv("train2.csv")

data.head(100)


data=np.array(data)

m,n=data.shape
np.random.shuffle(data)
dev=data[1:1000].T
ydev=dev[0]
xdev=dev[1:n]/255
train=data[1000:m].T
ytrain=train[0]
xtrain=train[1:n]/255




def init_param():
    w1=np.random.rand(10,784)-0.5
    b1=np.random.rand(10,1)-0.5
    w2=np.random.rand(10,10)-0.5
    b2=np.random.rand(10,1)-0.5
    return w1,w2,b1,b2

def Relu(Z):
    return np.maximum(0,Z)

def softMax(p1):
    return np.exp(p1)/np.sum(np.exp(p1),axis=0)

def forward_prop(w1,b1,w2,b2,X):
    Z1=w1.dot(X)+b1
    
    A1=Relu(Z1)
    Z2=w2.dot(A1)+b2
    A2=softMax(Z2)
    return Z1,A1,Z2,A2

def one_hot(Y):
    one_hot=np.zeros((Y.size,Y.max()+1));
    one_hot[np.arange(Y.size),Y]=1
    return one_hot.T

def dRelu(x):
    return x>0
        
def back_prop(Z1,A1,Z2,A2,Y,W2,X):
    m=Y.size
    onehot=one_hot(Y)
    dZ2=A2-onehot
    dW2=1/m*dZ2.dot(A1.T)
    dB2=1/m*np.sum(dZ2,axis=1,keepdims=True)
    dZ1=W2.T.dot(dZ2)*dRelu(Z1)
    dW1=1/m*dZ1.dot(X.T)
    dB1=1/m*np.sum(dZ1,axis=1,keepdims=True)
    return dZ2,dW2,dB2,dZ1,dW1,dB1

def update_param(w1,w2,b1,b2,dw1,dw2,db1,db2,alpha):
    w1=w1-alpha*dw1
    b1=b1-alpha*db1
  
    w2=w2-alpha*dw2
    b2=b2-alpha*db2
    return w1,b1,w2,b2

def get_pred(A2):
    return np.argmax(A2,0)

def get_accuracy(prediction,y):
    print(prediction,y)
    return np.sum(prediction==y)/y.size


def gradient_desc(x,y,itera,alpha):
    w1,w2,b1,b2=init_param()
    print(x.shape)
    for i in range(itera):
        
       
        Z1,A1,Z2,A2=forward_prop(w1,b1,w2,b2,x)
        dZ2,dW2,dB2,dZ1,dW1,dB1=back_prop(Z1,A1,Z2,A2,y,w2,x)
        w1,b1,w2,b2=update_param(w1,w2,b1,b2,dW1,dW2,dB1,dB2,alpha)
        if(i%10==0):
            print("\n-------\n")
            print("Round: ",i)
            print("Accuracy",get_accuracy(get_pred(A2),y))
    return w1,w2,b1,b2

w1,w2,b1,b2=gradient_desc(xtrain,ytrain,500,0.1)

(784, 41000)

-------

Round:  0
[1 6 6 ... 7 6 7] [4 4 8 ... 6 4 2]
Accuracy 0.13619512195121952

-------

Round:  10
[1 6 6 ... 8 6 8] [4 4 8 ... 6 4 2]
Accuracy 0.17973170731707316

-------

Round:  20
[1 6 6 ... 8 6 8] [4 4 8 ... 6 4 2]
Accuracy 0.24236585365853658

-------

Round:  30
[1 6 6 ... 6 6 8] [4 4 8 ... 6 4 2]
Accuracy 0.31597560975609756

-------

Round:  40
[9 6 6 ... 6 6 0] [4 4 8 ... 6 4 2]
Accuracy 0.37726829268292683

-------

Round:  50
[4 6 6 ... 6 9 0] [4 4 8 ... 6 4 2]
Accuracy 0.43521951219512195

-------

Round:  60
[4 6 6 ... 6 9 8] [4 4 8 ... 6 4 2]
Accuracy 0.48790243902439023

-------

Round:  70
[4 6 8 ... 6 9 2] [4 4 8 ... 6 4 2]
Accuracy 0.5232926829268293

-------

Round:  80
[4 6 8 ... 6 9 2] [4 4 8 ... 6 4 2]
Accuracy 0.5545853658536586

-------

Round:  90
[4 6 8 ... 6 9 2] [4 4 8 ... 6 4 2]
Accuracy 0.5815365853658536

-------

Round:  100
[4 6 8 ... 6 9 2] [4 4 8 ... 6 4 2]
Accuracy 0.6052682926829268

-------

Round:  110
[4 6 8 ... 6 4 2] [4 4 

In [11]:

Z1,A1,Z2,A2=forward_prop(w1,b1,w2,b2,xdev)

In [12]:
Y=np.argmax(A2,0)

In [13]:
Y.shape

(999,)

In [14]:
A2.shape

(10, 999)

In [26]:

def test():
    error=0
    for i in range(ydev.size):
        print("\nLabel:",ydev[i],"\nPrediction:",Y[i])
        if(ydev[i]-Y[i]!=0):
            error+=1

    print("\n\nTotal Errors:",error)

In [27]:
test()


Label: 1 
Prediction: 1

Label: 6 
Prediction: 5

Label: 1 
Prediction: 1

Label: 6 
Prediction: 6

Label: 1 
Prediction: 1

Label: 9 
Prediction: 4

Label: 7 
Prediction: 7

Label: 3 
Prediction: 3

Label: 9 
Prediction: 9

Label: 0 
Prediction: 0

Label: 8 
Prediction: 2

Label: 9 
Prediction: 9

Label: 1 
Prediction: 1

Label: 9 
Prediction: 9

Label: 0 
Prediction: 0

Label: 7 
Prediction: 7

Label: 6 
Prediction: 6

Label: 3 
Prediction: 3

Label: 0 
Prediction: 0

Label: 3 
Prediction: 3

Label: 1 
Prediction: 1

Label: 1 
Prediction: 1

Label: 1 
Prediction: 1

Label: 7 
Prediction: 7

Label: 2 
Prediction: 2

Label: 8 
Prediction: 5

Label: 6 
Prediction: 6

Label: 9 
Prediction: 9

Label: 4 
Prediction: 4

Label: 8 
Prediction: 8

Label: 0 
Prediction: 0

Label: 1 
Prediction: 1

Label: 3 
Prediction: 3

Label: 6 
Prediction: 6

Label: 2 
Prediction: 3

Label: 7 
Prediction: 7

Label: 0 
Prediction: 0

Label: 0 
Prediction: 0

Label: 5 
Prediction: 5

Label: 5 
Prediction: 5
